name: hommie
description: A social real estate app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  webview_flutter: ^4.7.0
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  flutter_dotenv: ^5.2.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0
  flutter_launcher_icons: ^0.14.4
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  lottie: ^2.7.0
  http: ^1.5.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  share_plus: ^10.0.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_cache_manager: ^3.3.2
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome_background.png
    - assets/avatars/
    - assets/images/home_screen.png
    - assets/images/welcome_background.jpg
    - assets/animations/clouds.json
    - .env
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/hommie_icon.png"
