default_platform(:android)

platform :android do
  desc "Build release AAB"
  lane :aab do
    gradle(task: "clean")
    gradle(task: "bundle", build_type: "Release")
    # Output will be at:
    # android/app/build/outputs/bundle/release/app-release.aab
  end
end

